config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :accounts
end

app/models/account.rb
class Account < ApplicationRecord
  validates :name, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all

    respond_to do |f|
      f.html
      f.json { render json: @accounts }
    end
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)

    respond_to do |f|
      if @account.save
        f.html
        f.json { render json: @account }
      else
        f.html
        f.json { render json: @account } # Errors?
      end
    end
  end

  def show
    @account = find_account

    respond_to do |f|
      f.html
      f.json { render json: @account }
    end
  end

  def update
    @account = find_account

    respond_to do |f|
      if @account.update_attributes(account_params)
        f.html
        f.json { render json: @account }
      else
        f.html
        f.json { render json: @account } # Errors?
      end
    end
  end

  def destroy
    find_account.destroy

    respond_do do |f|
      f.html
      f.json { render json: '' } # what goes here?
    end
  end

private

  def find_account
    Account.where(id: params[:id]).first
  end

  def account_params
    params.require(:account).permit(:name, :type)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/index.html.erb
<script type='statebus'>
  dom.ACCOUNTS = ->
    accounts = fetch('/accounts')

    DIV null,
      P null,
        'This page shows the '
        CODE 'html'
        ' response.'

      P null,
        'View the JSON response '
        A
          href: "<%= accounts_path(format: 'json') %>"
          'here.'

      H1 'Accounts'

      unless loading()
        OL null,
          for account in accounts.results || [] # Why do we need this? Loading() doesn't seem to work
            LI account.name

</script> 


<ACCOUNTS></ACCOUNTS>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Statebus-Rails Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/3.0.1/github-markdown.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='markdown-body'>
    <%= yield %>
  </body>
</html>